"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const showHeader = ! pathname.startsWith('/dashboard') 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ` }
      >
        {showHeader &&  
        <Header/>
        }
        
        <div className="">
        {children}
        </div>
        {/* <Footer/> */}
          <Toaster danger='red' succees='green' />
      </body>
    </html>
  );
}
